name: nzk
description: "A Seventh day adventist hymns swahili hymns app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1
  google_fonts: ^8.1.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/swahili.json

flutter_native_splash:
  color: "#F9F9F9"
  color_dark: "#121212"
  image: "assets/images/splashlight.png"
  image_dark: "assets/images/splashdark.png"
  android_12:
    color: "#F9F9F9"
    color_dark: "#121212"
    image: "assets/images/splashlight.png"
    image_dark: "assets/images/splashdark.png"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/iconlight.png"
  remove_alpha_ios: true
  image_path_ios_dark: "assets/images/icondark.png"
  adaptive_icon_background: "#F9F9F9"
  adaptive_icon_foreground: "assets/images/splashlight.png"
  adaptive_icon_monochrome: "assets/images/splashdark.png"
